/* =========================================================================
   NGÂN HÀNG 300 CÂU LUYỆN ĐỌC TRƠN LỚP 1 (3 CẤP ĐỘ x 100 CÂU)
   ========================================================================= */
const QUESTION_BANK = {
  level1: [
    { id: 101, text: "Bé đi học.", emoji: "🎒", guide: "Đọc liền mạch 3 tiếng rõ ràng", theme: "from-rose-200 via-pink-100 to-amber-200", textColor: "text-rose-800" },
    { id: 102, text: "Mẹ đi chợ.", emoji: "🧺", guide: "Đọc to, dứt khoát 3 tiếng", theme: "from-amber-200 via-orange-100 to-yellow-200", textColor: "text-amber-900" },
    { id: 103, text: "Ba mua xe.", emoji: "🚲", guide: "Đọc vui vẻ, liền mạch", theme: "from-emerald-200 via-teal-100 to-green-200", textColor: "text-emerald-900" },
    { id: 104, text: "Bà bế bé.", emoji: "👶", guide: "Giọng đọc ngọt ngào, ấm áp", theme: "from-sky-200 via-blue-100 to-cyan-200", textColor: "text-sky-900" },
    { id: 105, text: "Cá bơi lội.", emoji: "🐟", guide: "Chú ý phân biệt vần: ơi - ôi", theme: "from-purple-200 via-violet-100 to-pink-200", textColor: "text-purple-900" },
    { id: 106, text: "Gà gáy te te.", emoji: "🐓", guide: "Âm g đọc vang, rõ tiếng", theme: "from-orange-200 via-amber-100 to-rose-200", textColor: "text-orange-900" },
    { id: 107, text: "Bé có cặp da.", emoji: "👜", guide: "Ngắt nhịp: Bé có / cặp da", theme: "from-teal-200 via-cyan-100 to-emerald-200", textColor: "text-teal-900" },
    { id: 108, text: "Vở bé sạch.", emoji: "📒", guide: "Âm s đọc chuẩn: sạch", theme: "from-indigo-200 via-sky-100 to-blue-200", textColor: "text-indigo-900" },
    { id: 109, text: "Chữ bé đẹp.", emoji: "✍️", guide: "Đọc tròn tiếng: chữ bé đẹp", theme: "from-rose-200 via-pink-100 to-red-200", textColor: "text-rose-900" },
    { id: 110, text: "Bé rất ngoan.", emoji: "😇", guide: "Vần oan tròn môi: ngoan", theme: "from-amber-200 via-yellow-100 to-lime-200", textColor: "text-amber-900" },
    { id: 111, text: "Mèo con ngủ.", emoji: "🐱", guide: "Đọc chậm rãi, liền mạch", theme: "from-sky-200 via-indigo-100 to-blue-200", textColor: "text-sky-900" },
    { id: 112, text: "Chó giữ nhà.", emoji: "🐶", guide: "Âm gi trong từ: giữ nhà", theme: "from-amber-200 via-orange-100 to-yellow-200", textColor: "text-amber-900" },
    { id: 113, text: "Nắng mai ấm.", emoji: "☀️", guide: "Âm n đọc chuẩn: nắng mai", theme: "from-yellow-200 via-amber-100 to-orange-200", textColor: "text-amber-800" },
    { id: 114, text: "Gió mát quá.", emoji: "🍃", guide: "Vần at trong tiếng: mát", theme: "from-teal-200 via-cyan-100 to-emerald-200", textColor: "text-teal-900" },
    { id: 115, text: "Bé rửa tay.", emoji: "🧼", guide: "Đọc to rõ: bé rửa tay", theme: "from-cyan-200 via-teal-100 to-emerald-200", textColor: "text-teal-900" },
    { id: 116, text: "Bé ăn cơm.", emoji: "🍚", guide: "Đọc lưu loát 3 tiếng", theme: "from-orange-200 via-rose-100 to-amber-200", textColor: "text-orange-900" },
    { id: 117, text: "Lá xanh biếc.", emoji: "🌿", guide: "Âm l đọc chắc: lá xanh", theme: "from-emerald-200 via-green-100 to-lime-200", textColor: "text-emerald-900" },
    { id: 118, text: "Bé đọc to.", emoji: "📖", guide: "Dứt khoát: bé đọc to", theme: "from-rose-200 via-amber-100 to-pink-200", textColor: "text-rose-900" },
    { id: 119, text: "Mẹ may áo.", emoji: "🧵", guide: "Vần ay trong tiếng: may áo", theme: "from-pink-200 via-purple-100 to-rose-200", textColor: "text-pink-900" },
    { id: 120, text: "Ba tưới cây.", emoji: "🪴", guide: "Vần ươi và ay: tưới cây", theme: "from-green-200 via-emerald-100 to-teal-200", textColor: "text-green-900" },
    { id: 121, text: "Bé vẽ hoa.", emoji: "🌸", guide: "Vần oa tròn môi: vẽ hoa", theme: "from-rose-200 via-pink-100 to-amber-200", textColor: "text-rose-800" },
    { id: 122, text: "Quả cam ngọt.", emoji: "🍊", guide: "Âm qu và vần am: quả cam", theme: "from-amber-200 via-orange-100 to-yellow-200", textColor: "text-amber-900" },
    { id: 123, text: "Bé quét nhà.", emoji: "🧹", guide: "Vần et trong tiếng: quét nhà", theme: "from-emerald-200 via-teal-100 to-green-200", textColor: "text-emerald-900" },
    { id: 124, text: "Chim hót hay.", emoji: "🐦", guide: "Vần im và ay: chim hót hay", theme: "from-sky-200 via-blue-100 to-cyan-200", textColor: "text-sky-900" },
    { id: 125, text: "Em cười tươi.", emoji: "😄", guide: "Vần ươi trong tiếng: cười tươi", theme: "from-purple-200 via-violet-100 to-pink-200", textColor: "text-purple-900" },
    { id: 126, text: "Vịt bơi nhanh.", emoji: "🦆", guide: "Âm v và vần anh: bơi nhanh", theme: "from-orange-200 via-amber-100 to-rose-200", textColor: "text-orange-900" },
    { id: 127, text: "Bé xếp hàng.", emoji: "👫", guide: "Vần ang trong tiếng: xếp hàng", theme: "from-teal-200 via-cyan-100 to-emerald-200", textColor: "text-teal-900" },
    { id: 128, text: "Trời mưa rồi.", emoji: "🌧️", guide: "Âm tr uốn cong nhẹ: trời mưa", theme: "from-indigo-200 via-sky-100 to-blue-200", textColor: "text-indigo-900" },
    { id: 129, text: "Bé nhảy dây.", emoji: "🪢", guide: "Dấu hỏi ở tiếng: nhảy dây", theme: "from-rose-200 via-pink-100 to-red-200", textColor: "text-rose-900" },
    { id: 130, text: "Bàn học gỗ.", emoji: "🪑", guide: "Dấu ngã ở tiếng: gỗ", theme: "from-amber-200 via-yellow-100 to-lime-200", textColor: "text-amber-900" },
    { id: 131, text: "Bé soi gương.", emoji: "🪞", guide: "Vần ương trong tiếng: soi gương", theme: "from-sky-200 via-indigo-100 to-blue-200", textColor: "text-sky-900" },
    { id: 132, text: "Đèn bàn sáng.", emoji: "💡", guide: "Âm s trong tiếng: sáng", theme: "from-amber-200 via-orange-100 to-yellow-200", textColor: "text-amber-900" },
    { id: 133, text: "Quả mít chín.", emoji: "🍈", guide: "Âm qu và vần it: quả mít chín", theme: "from-yellow-200 via-amber-100 to-orange-200", textColor: "text-amber-800" },
    { id: 134, text: "Bò kéo xe.", emoji: "🐂", guide: "Đọc 3 tiếng dứt khoát: bò kéo xe", theme: "from-teal-200 via-cyan-100 to-emerald-200", textColor: "text-teal-900" },
    { id: 135, text: "Bé tập đếm.", emoji: "🔢", guide: "Vần âm và vần em: tập đếm", theme: "from-cyan-200 via-teal-100 to-emerald-200", textColor: "text-teal-900" },
    { id: 136, text: "Cá rô phi.", emoji: "🐟", guide: "Âm r rung nhẹ: cá rô phi", theme: "from-orange-200 via-rose-100 to-amber-200", textColor: "text-orange-900" },
    { id: 137, text: "Mẹ ru bé.", emoji: "🤱", guide: "Âm r trong tiếng: ru bé", theme: "from-emerald-200 via-green-100 to-lime-200", textColor: "text-emerald-900" },
    { id: 138, text: "Bé đánh răng.", emoji: "🪥", guide: "Vần anh và vần ăng: đánh răng", theme: "from-rose-200 via-amber-100 to-pink-200", textColor: "text-rose-900" },
    { id: 139, text: "Bé đi ngủ.", emoji: "🛏️", guide: "Dấu hỏi ở tiếng: ngủ", theme: "from-pink-200 via-purple-100 to-rose-200", textColor: "text-pink-900" },
    { id: 140, text: "Bình hoa đẹp.", emoji: "🏺", guide: "Vần inh và vần oa: bình hoa", theme: "from-green-200 via-emerald-100 to-teal-200", textColor: "text-green-900" },
    { id: 141, text: "Bé cài nơ.", emoji: "🎀", guide: "Âm n đọc chuẩn: cài nơ", theme: "from-rose-200 via-pink-100 to-amber-200", textColor: "text-rose-800" },
    { id: 142, text: "Quả na chín.", emoji: "🍐", guide: "Âm qu và n: quả na chín", theme: "from-amber-200 via-orange-100 to-yellow-200", textColor: "text-amber-900" },
    { id: 143, text: "Cún con sủa.", emoji: "🐕", guide: "Âm s và dấu hỏi: sủa", theme: "from-emerald-200 via-teal-100 to-green-200", textColor: "text-emerald-900" },
    { id: 144, text: "Đồng hồ reo.", emoji: "⏰", guide: "Âm r trong tiếng: reo", theme: "from-sky-200 via-blue-100 to-cyan-200", textColor: "text-sky-900" },
    { id: 145, text: "Bé vâng lời.", emoji: "🙏", guide: "Âm v và l: vâng lời", theme: "from-purple-200 via-violet-100 to-pink-200", textColor: "text-purple-900" },
    { id: 146, text: "Bé xách xô.", emoji: "🪣", guide: "Âm x đọc nhẹ: xách xô", theme: "from-orange-200 via-amber-100 to-rose-200", textColor: "text-orange-900" },
    { id: 147, text: "Bé nhai kĩ.", emoji: "🥣", guide: "Dấu ngã gằn nhẹ: nhai kĩ", theme: "from-teal-200 via-cyan-100 to-emerald-200", textColor: "text-teal-900" },
    { id: 148, text: "Ngựa phi nhanh.", emoji: "🐎", guide: "Vần anh trong tiếng: phi nhanh", theme: "from-indigo-200 via-sky-100 to-blue-200", textColor: "text-indigo-900" },
    { id: 149, text: "Bé tập vẽ.", emoji: "🖍️", guide: "Dấu ngã ở tiếng: vẽ", theme: "from-rose-200 via-pink-100 to-red-200", textColor: "text-rose-900" },
    { id: 150, text: "Bé ngoan lắm.", emoji: "🥰", guide: "Tròn môi: ngoan lắm", theme: "from-amber-200 via-yellow-100 to-lime-200", textColor: "text-amber-900" },
    { id: 151, text: "Bé chào cô.", emoji: "👩‍🏫", guide: "Âm ch và c: chào cô", theme: "from-rose-200 via-pink-100 to-amber-200", textColor: "text-rose-800" },
    { id: 152, text: "Bé rửa mặt.", emoji: "🧼", guide: "Vần ưa và vần ăt: rửa mặt", theme: "from-sky-200 via-blue-100 to-cyan-200", textColor: "text-sky-900" },
    { id: 153, text: "Bé chải đầu.", emoji: "🪮", guide: "Vần ai và vần âu: chải đầu", theme: "from-emerald-200 via-teal-100 to-green-200", textColor: "text-emerald-900" },
    { id: 154, text: "Cá chép đỏ.", emoji: "🐠", guide: "Vần ep: cá chép đỏ", theme: "from-amber-200 via-orange-100 to-yellow-200", textColor: "text-amber-900" },
    { id: 155, text: "Nụ hoa hồng.", emoji: "🌹", guide: "Âm n và vần ong: hoa hồng", theme: "from-purple-200 via-violet-100 to-pink-200", textColor: "text-purple-900" },
    { id: 156, text: "Bé có ô.", emoji: "☂️", guide: "Âm ô tròn môi rõ ràng", theme: "from-teal-200 via-cyan-100 to-emerald-200", textColor: "text-teal-900" },
    { id: 157, text: "Mẹ pha trà.", emoji: "🍵", guide: "Âm ph và tr: pha trà", theme: "from-indigo-200 via-sky-100 to-blue-200", textColor: "text-indigo-900" },
    { id: 158, text: "Bố lái xe.", emoji: "🚗", guide: "Vần ai: bố lái xe", theme: "from-orange-200 via-amber-100 to-rose-200", textColor: "text-orange-900" },
    { id: 159, text: "Bé vỗ tay.", emoji: "👏", guide: "Dấu ngã ở tiếng: vỗ tay", theme: "from-rose-200 via-pink-100 to-red-200", textColor: "text-rose-900" },
    { id: 160, text: "Cây có quả.", emoji: "🍎", guide: "Âm c và qu: có quả", theme: "from-amber-200 via-yellow-100 to-lime-200", textColor: "text-amber-900" },
    { id: 161, text: "Bé ôm bà.", emoji: "👵", guide: "Vần ôm: bé ôm bà", theme: "from-sky-200 via-indigo-100 to-blue-200", textColor: "text-sky-900" },
    { id: 162, text: "Bé có bi.", emoji: "🔮", guide: "Đọc dứt khoát 3 tiếng", theme: "from-teal-200 via-cyan-100 to-emerald-200", textColor: "text-teal-900" },
    { id: 163, text: "Mèo bắt chuột.", emoji: "🐈", guide: "Vần uôt: bắt chuột", theme: "from-amber-200 via-orange-100 to-yellow-200", textColor: "text-amber-900" },
    { id: 164, text: "Gà mổ thóc.", emoji: "🌾", guide: "Vần oc: gà mổ thóc", theme: "from-yellow-200 via-amber-100 to-orange-200", textColor: "text-amber-800" },
    { id: 165, text: "Bé vẽ tranh.", emoji: "🖼️", guide: "Âm tr và vần anh: tranh", theme: "from-cyan-200 via-teal-100 to-emerald-200", textColor: "text-teal-900" },
    { id: 166, text: "Bé thổi kèn.", emoji: "🎺", guide: "Vần oi và en: thổi kèn", theme: "from-orange-200 via-rose-100 to-amber-200", textColor: "text-orange-900" },
    { id: 167, text: "Trăng tròn xoe.", emoji: "🌕", guide: "Âm tr và tròn môi: xoe", theme: "from-purple-200 via-pink-100 to-rose-200", textColor: "text-purple-900" },
    { id: 168, text: "Bé hát ca.", emoji: "🎤", guide: "Vần at: bé hát ca", theme: "from-emerald-200 via-green-100 to-lime-200", textColor: "text-emerald-900" },
    { id: 169, text: "Cá quẫy đuôi.", emoji: "🏊", guide: "Vần uôi và âm qu: quẫy đuôi", theme: "from-sky-200 via-blue-100 to-cyan-200", textColor: "text-sky-900" },
    { id: 170, text: "Mẹ may đầm.", emoji: "👗", guide: "Vần âm: may đầm", theme: "from-pink-200 via-purple-100 to-rose-200", textColor: "text-pink-900" },
    { id: 171, text: "Bé gấp chăn.", emoji: "🛏️", guide: "Vần ăp và ăn: gấp chăn", theme: "from-green-200 via-emerald-100 to-teal-200", textColor: "text-green-900" },
    { id: 172, text: "Bé mang giày.", emoji: "👟", guide: "Vần ang và ay: mang giày", theme: "from-rose-200 via-pink-100 to-amber-200", textColor: "text-rose-800" },
    { id: 173, text: "Hoa cúc vàng.", emoji: "🌼", guide: "Vần uc và ang: cúc vàng", theme: "from-amber-200 via-orange-100 to-yellow-200", textColor: "text-amber-900" },
    { id: 174, text: "Bé uống sữa.", emoji: "🥛", guide: "Dấu ngã ở tiếng: sữa", theme: "from-teal-200 via-cyan-100 to-emerald-200", textColor: "text-teal-900" },
    { id: 175, text: "Bé ăn táo.", emoji: "🍎", guide: "Vần ao: ăn táo", theme: "from-rose-200 via-pink-100 to-red-200", textColor: "text-rose-900" },
    { id: 176, text: "Bé nhớ mẹ.", emoji: "❤️", guide: "Dấu sắc và dấu hỏi: nhớ mẹ", theme: "from-indigo-200 via-sky-100 to-blue-200", textColor: "text-indigo-900" },
    { id: 177, text: "Bướm lượn quanh.", emoji: "🦋", guide: "Vần ươm và vần uơn: lượn", theme: "from-purple-200 via-violet-100 to-pink-200", textColor: "text-purple-900" },
    { id: 178, text: "Trời xanh biếc.", emoji: "🌤️", guide: "Âm tr và vần iêc: xanh biếc", theme: "from-sky-200 via-blue-100 to-cyan-200", textColor: "text-sky-900" },
    { id: 179, text: "Tay bé sạch.", emoji: "🧼", guide: "Âm s đọc chuẩn: tay bé sạch", theme: "from-emerald-200 via-teal-100 to-green-200", textColor: "text-emerald-900" },
    { id: 180, text: "Bé đi dạo.", emoji: "🚶", guide: "Âm d và vần ao: đi dạo", theme: "from-amber-200 via-yellow-100 to-lime-200", textColor: "text-amber-900" },
    { id: 181, text: "Ong tìm mật.", emoji: "🐝", guide: "Vần ong và ăt: tìm mật", theme: "from-orange-200 via-amber-100 to-rose-200", textColor: "text-orange-900" },
    { id: 182, text: "Bé lau bàn.", emoji: "🧽", guide: "Vần au và an: lau bàn", theme: "from-teal-200 via-cyan-100 to-emerald-200", textColor: "text-teal-900" },
    { id: 183, text: "Bé rửa chân.", emoji: "🦶", guide: "Âm ch và vần ân: rửa chân", theme: "from-cyan-200 via-teal-100 to-emerald-200", textColor: "text-teal-900" },
    { id: 184, text: "Chuối chín vàng.", emoji: "🍌", guide: "Vần uôi và in: chuối chín", theme: "from-yellow-200 via-amber-100 to-orange-200", textColor: "text-amber-800" },
    { id: 185, text: "Bé mặc ấm.", emoji: "🧣", guide: "Vần ăc và âm: mặc ấm", theme: "from-rose-200 via-amber-100 to-pink-200", textColor: "text-rose-900" },
    { id: 186, text: "Gà kêu chiếp.", emoji: "🐥", guide: "Vần iêp: gà kêu chiếp", theme: "from-amber-200 via-orange-100 to-yellow-200", textColor: "text-amber-900" },
    { id: 187, text: "Bé khoanh tay.", emoji: "🙇", guide: "Vần oanh tròn môi: khoanh", theme: "from-emerald-200 via-green-100 to-lime-200", textColor: "text-emerald-900" },
    { id: 188, text: "Bé dừng đèn đỏ.", emoji: "🚦", guide: "Vần ưng và vần e: dừng đèn đỏ", theme: "from-rose-200 via-pink-100 to-red-200", textColor: "text-rose-900" },
    { id: 189, text: "Bé tưới rau.", emoji: "🌱", guide: "Vần ươi và au: tưới rau", theme: "from-green-200 via-emerald-100 to-teal-200", textColor: "text-green-900" },
    { id: 190, text: "Bé quét sân.", emoji: "🧹", guide: "Vần et và ân: quét sân", theme: "from-teal-200 via-cyan-100 to-emerald-200", textColor: "text-teal-900" },
    { id: 191, text: "Sách mở ra.", emoji: "📖", guide: "Âm s đọc chuẩn: sách mở", theme: "from-sky-200 via-indigo-100 to-blue-200", textColor: "text-sky-900" },
    { id: 192, text: "Bé viết bài.", emoji: "📝", guide: "Vần iêt và ai: viết bài", theme: "from-indigo-200 via-sky-100 to-blue-200", textColor: "text-indigo-900" },
    { id: 193, text: "Hoa sen hồng.", emoji: "🪷", guide: "Vần en và ong: sen hồng", theme: "from-pink-200 via-rose-100 to-purple-200", textColor: "text-pink-900" },
    { id: 194, text: "Mây trắng bay.", emoji: "☁️", guide: "Âm tr và vần ay: mây trắng", theme: "from-sky-200 via-blue-100 to-cyan-200", textColor: "text-sky-900" },
    { id: 195, text: "Bé xếp vở.", emoji: "📚", guide: "Âm x: xếp vở", theme: "from-purple-200 via-violet-100 to-pink-200", textColor: "text-purple-900" },
    { id: 196, text: "Bé mỉm cười.", emoji: "😊", guide: "Vần im và ươi: mỉm cười", theme: "from-rose-200 via-pink-100 to-amber-200", textColor: "text-rose-800" },
    { id: 197, text: "Bé rất vui.", emoji: "🎉", guide: "Vần ui: bé rất vui", theme: "from-amber-200 via-yellow-100 to-lime-200", textColor: "text-amber-900" },
    { id: 198, text: "Mẹ yêu bé.", emoji: "👩‍👧", guide: "Vần yêu: mẹ yêu bé", theme: "from-rose-200 via-pink-100 to-red-200", textColor: "text-rose-900" },
    { id: 199, text: "Bé chăm học.", emoji: "🎓", guide: "Âm ch và vần oc: chăm học", theme: "from-emerald-200 via-teal-100 to-green-200", textColor: "text-emerald-900" },
    { id: 200, text: "Bé ngoan nhất.", emoji: "🥇", guide: "Tròn môi vần oan: ngoan nhất", theme: "from-amber-300 via-yellow-200 to-amber-200", textColor: "text-amber-950" }
  ],
  level2: [
    { id: 201, text: "Bé giúp mẹ nhặt rau.", emoji: "🥬", guide: "Ngắt nhịp: Bé giúp mẹ / nhặt rau", theme: "from-green-200 via-lime-100 to-emerald-200", textColor: "text-green-900" },
    { id: 202, text: "Bố sửa bàn học cho bé.", emoji: "🪑", guide: "Nhấn dấu ngã: sửa bàn", theme: "from-sky-200 via-teal-100 to-cyan-200", textColor: "text-sky-900" },
    { id: 203, text: "Ông ngồi uống trà ấm.", emoji: "🍵", guide: "Âm tr uốn nhẹ: trà ấm", theme: "from-amber-200 via-yellow-100 to-orange-200", textColor: "text-amber-900" },
    { id: 204, text: "Bà kể chuyện cổ tích.", emoji: "👵", guide: "Vần uyên trong tiếng: chuyện", theme: "from-purple-200 via-pink-100 to-rose-200", textColor: "text-purple-900" },
    { id: 205, text: "Em bé ngủ rất say.", emoji: "😴", guide: "Âm s nhẹ nhàng, chậm rãi", theme: "from-rose-200 via-pink-100 to-indigo-200", textColor: "text-rose-900" },
    { id: 206, text: "Hộp bút có thước kẻ.", emoji: "📏", guide: "Vần ươc: thước kẻ", theme: "from-teal-200 via-emerald-100 to-green-200", textColor: "text-teal-900" },
    { id: 207, text: "Bút chì đã gọt nhọn.", emoji: "✏️", guide: "Đọc liền cụm: gọt nhọn", theme: "from-orange-200 via-amber-100 to-yellow-200", textColor: "text-orange-900" },
    { id: 208, text: "Bé tô màu bông hoa.", emoji: "🎨", guide: "Tròn môi: bông hoa", theme: "from-indigo-200 via-sky-100 to-cyan-200", textColor: "text-indigo-900" },
    { id: 209, text: "Mặt trời mọc đằng đông.", emoji: "🌅", guide: "Âm tr chắc tiếng: mặt trời", theme: "from-yellow-200 via-orange-100 to-rose-200", textColor: "text-amber-900" },
    { id: 210, text: "Bầu trời hôm nay xanh ngắt.", emoji: "☁️", guide: "Vần ăt trong tiếng: xanh ngắt", theme: "from-sky-200 via-blue-100 to-indigo-200", textColor: "text-sky-900" },
    { id: 211, text: "Đàn chim bay về tổ.", emoji: "🕊️", guide: "Đọc liền 5 tiếng êm ái", theme: "from-purple-200 via-violet-100 to-sky-200", textColor: "text-purple-900" },
    { id: 212, text: "Dòng suối nhỏ chảy róc rách.", emoji: "💧", guide: "Từ láy mô phỏng: róc rách", theme: "from-teal-200 via-cyan-100 to-blue-200", textColor: "text-teal-900" },
    { id: 213, text: "Vườn nhà nở đầy hoa.", emoji: "🌺", guide: "Vần ươn trong tiếng: vườn", theme: "from-rose-200 via-pink-100 to-amber-200", textColor: "text-rose-900" },
    { id: 214, text: "Cây khế ngọt trĩu cành.", emoji: "⭐", guide: "Dấu ngã ở tiếng: trĩu", theme: "from-emerald-200 via-green-100 to-teal-200", textColor: "text-emerald-900" },
    { id: 215, text: "Bé chào mẹ khi đi học.", emoji: "🙋‍♂️", guide: "Ngắt: Bé chào mẹ / khi đi học", theme: "from-amber-200 via-yellow-100 to-orange-200", textColor: "text-amber-900" },
    { id: 216, text: "Tiếng trống trường vang giòn giã.", emoji: "🥁", guide: "Âm tr và dấu ngã: giòn giã", theme: "from-orange-200 via-red-100 to-amber-200", textColor: "text-orange-900" },
    { id: 217, text: "Các bạn cùng xếp hàng.", emoji: "👫", guide: "Vần ang trong tiếng: xếp hàng", theme: "from-sky-200 via-indigo-100 to-blue-200", textColor: "text-sky-900" },
    { id: 218, text: "Lớp học thật ngăn nắp.", emoji: "🏫", guide: "Vần ắp trong từ: ngăn nắp", theme: "from-indigo-200 via-purple-100 to-teal-200", textColor: "text-indigo-900" },
    { id: 219, text: "Bé lắng nghe cô giảng.", emoji: "👂", guide: "Phân biệt vần: ăng - ang", theme: "from-rose-200 via-amber-100 to-yellow-200", textColor: "text-rose-900" },
    { id: 220, text: "Giờ ra chơi vui nhộn.", emoji: "⚽", guide: "Đọc tươi vui, dứt khoát", theme: "from-green-200 via-emerald-100 to-lime-200", textColor: "text-green-900" },
    { id: 221, text: "Bé gấp chăn màn gọn gàng.", emoji: "🛌", guide: "Từ láy: gọn gàng", theme: "from-teal-200 via-cyan-100 to-emerald-200", textColor: "text-teal-900" },
    { id: 222, text: "Bé cất bát đĩa sau bữa ăn.", emoji: "🥣", guide: "Dấu ngã: bát đĩa / bữa ăn", theme: "from-orange-200 via-rose-100 to-amber-200", textColor: "text-orange-900" },
    { id: 223, text: "Chú mèo vồ bóng len.", emoji: "🧶", guide: "Âm v và l: bóng len", theme: "from-pink-200 via-rose-100 to-purple-200", textColor: "text-pink-900" },
    { id: 224, text: "Đàn cá tung tăng bơi.", emoji: "🐠", guide: "Từ láy: tung tăng bơi", theme: "from-sky-200 via-blue-100 to-cyan-200", textColor: "text-sky-900" },
    { id: 225, text: "Mẹ pha sữa ấm cho em.", emoji: "🥛", guide: "Dấu ngã: pha sữa ấm", theme: "from-purple-200 via-pink-100 to-rose-200", textColor: "text-purple-900" },
    { id: 226, text: "Bố dạy bé đi xe đạp.", emoji: "🚲", guide: "Đọc liền mạch 6 tiếng", theme: "from-emerald-200 via-teal-100 to-green-200", textColor: "text-emerald-900" },
    { id: 227, text: "Bà đan áo len cho bé.", emoji: "🧶", guide: "Âm đ và l: đan áo len", theme: "from-amber-200 via-orange-100 to-yellow-200", textColor: "text-amber-900" },
    { id: 228, text: "Bé tưới luống hoa cúc.", emoji: "🌼", guide: "Vần uông: luống hoa cúc", theme: "from-yellow-200 via-amber-100 to-orange-200", textColor: "text-amber-800" },
    { id: 229, text: "Góc học tập rất sáng.", emoji: "💡", guide: "Âm s: rất sáng", theme: "from-cyan-200 via-teal-100 to-emerald-200", textColor: "text-teal-900" },
    { id: 230, text: "Bé nắn nót từng chữ.", emoji: "📝", guide: "Dấu ngã: từng chữ", theme: "from-rose-200 via-pink-100 to-red-200", textColor: "text-rose-900" },
    { id: 231, text: "Thầy giáo đọc bài thơ.", emoji: "📜", guide: "Âm th và gi: thầy giáo", theme: "from-indigo-200 via-sky-100 to-blue-200", textColor: "text-indigo-900" },
    { id: 232, text: "Bạn Nam đọc bài to.", emoji: "👦", guide: "Âm n đọc chuẩn: bạn Nam", theme: "from-teal-200 via-emerald-100 to-green-200", textColor: "text-teal-900" },
    { id: 233, text: "Cả lớp cùng vỗ tay.", emoji: "👏", guide: "Dấu ngã ở tiếng: vỗ tay", theme: "from-amber-200 via-yellow-100 to-orange-200", textColor: "text-amber-900" },
    { id: 234, text: "Bé xếp sách vào cặp.", emoji: "🎒", guide: "Vần êp và ăp: xếp sách", theme: "from-rose-200 via-amber-100 to-pink-200", textColor: "text-rose-900" },
    { id: 235, text: "Cây bàng trút lá đỏ.", emoji: "🍂", guide: "Âm tr: trút lá đỏ", theme: "from-orange-200 via-amber-100 to-rose-200", textColor: "text-orange-900" },
    { id: 236, text: "Chim sâu bắt cào cào.", emoji: "🐛", guide: "Âm s và c: chim sâu", theme: "from-green-200 via-lime-100 to-emerald-200", textColor: "text-green-900" },
    { id: 237, text: "Bé chơi ô ăn quan.", emoji: "🎲", guide: "Vần an và oan: ăn quan", theme: "from-purple-200 via-violet-100 to-pink-200", textColor: "text-purple-900" },
    { id: 238, text: "Bé chia kẹo cho bạn.", emoji: "🍬", guide: "Vần ia và eo: chia kẹo", theme: "from-sky-200 via-indigo-100 to-blue-200", textColor: "text-sky-900" },
    { id: 239, text: "Mẹ khen bé chăm chỉ.", emoji: "⭐", guide: "Âm ch: chăm chỉ", theme: "from-pink-200 via-rose-100 to-amber-200", textColor: "text-pink-900" },
    { id: 240, text: "Bé yêu cả gia đình.", emoji: "❤️", guide: "Vần in và inh: gia đình", theme: "from-rose-200 via-pink-100 to-purple-200", textColor: "text-rose-900" },
    { id: 241, text: "Ông bà luôn vui tươi.", emoji: "🧓", guide: "Vần uôn và ươi: luôn vui tươi", theme: "from-amber-200 via-orange-100 to-yellow-200", textColor: "text-amber-900" },
    { id: 242, text: "Bé tưới rau sau hè.", emoji: "🌱", guide: "Vần ươi: tưới rau", theme: "from-emerald-200 via-teal-100 to-green-200", textColor: "text-emerald-900" },
    { id: 243, text: "Quả na chín mở mắt.", emoji: "🍈", guide: "Âm qu và n: quả na", theme: "from-yellow-200 via-amber-100 to-orange-200", textColor: "text-amber-800" },
    { id: 244, text: "Bé khoe điểm mười đỏ thắm.", emoji: "💯", guide: "Vần oe và ươi: khoe điểm mười", theme: "from-teal-200 via-cyan-100 to-emerald-200", textColor: "text-teal-900" },
    { id: 245, text: "Tiếng cười vui rộn rã.", emoji: "😆", guide: "Dấu ngã ở tiếng: rộn rã", theme: "from-rose-200 via-pink-100 to-red-200", textColor: "text-rose-900" },
    { id: 246, text: "Bé gọt bút cẩn thận.", emoji: "✏️", guide: "Ngắt: Bé gọt bút / cẩn thận", theme: "from-sky-200 via-blue-100 to-cyan-200", textColor: "text-sky-900" },
    { id: 247, text: "Hồ sen ngát hương thơm.", emoji: "🪷", guide: "Âm s và h: sen ngát hương", theme: "from-purple-200 via-pink-100 to-rose-200", textColor: "text-purple-900" },
    { id: 248, text: "Đàn lợn ăn no ngủ say.", emoji: "🐖", guide: "Âm l và s: đàn lợn / ngủ say", theme: "from-orange-200 via-amber-100 to-yellow-200", textColor: "text-orange-900" },
    { id: 249, text: "Bé chúc mẹ ngủ ngon.", emoji: "🌙", guide: "Âm ch và ng: ngủ ngon", theme: "from-indigo-200 via-purple-100 to-sky-200", textColor: "text-indigo-900" },
    { id: 250, text: "Bé thức giấc đúng giờ.", emoji: "⏰", guide: "Âm gi: đúng giờ", theme: "from-amber-200 via-yellow-100 to-lime-200", textColor: "text-amber-900" },
    { id: 251, text: "Bé đánh răng thật sạch.", emoji: "🪥", guide: "Âm đ và s: đánh răng sạch", theme: "from-sky-200 via-teal-100 to-cyan-200", textColor: "text-sky-900" },
    { id: 252, text: "Mẹ nấu xôi gấc đỏ.", emoji: "🍚", guide: "Vần ôi và ăc: xôi gấc", theme: "from-rose-200 via-pink-100 to-amber-200", textColor: "text-rose-900" },
    { id: 253, text: "Bố đóng đinh treo tranh.", emoji: "🔨", guide: "Âm đ và tr: đóng đinh / treo tranh", theme: "from-amber-200 via-yellow-100 to-orange-200", textColor: "text-amber-900" },
    { id: 254, text: "Bà xâu kim rất khéo.", emoji: "🪡", guide: "Âm x và kh: xâu kim khéo", theme: "from-purple-200 via-pink-100 to-rose-200", textColor: "text-purple-900" },
    { id: 255, text: "Bé cất sách vào ba lô.", emoji: "🎒", guide: "Ngắt nhịp: Bé cất sách / vào ba lô", theme: "from-teal-200 via-emerald-100 to-green-200", textColor: "text-teal-900" },
    { id: 256, text: "Mèo con chăm chỉ liếm lông.", emoji: "🐱", guide: "Âm l chuẩn: liếm lông", theme: "from-orange-200 via-amber-100 to-yellow-200", textColor: "text-orange-900" },
    { id: 257, text: "Cún vẫy đuôi mừng bố.", emoji: "🐕", guide: "Dấu ngã: vẫy đuôi", theme: "from-indigo-200 via-sky-100 to-cyan-200", textColor: "text-indigo-900" },
    { id: 258, text: "Bé rửa chén bát sạch sẽ.", emoji: "🥣", guide: "Âm ch và s: chén bát sạch sẽ", theme: "from-green-200 via-lime-100 to-emerald-200", textColor: "text-green-900" },
    { id: 259, text: "Hoa hồng tỏa hương thơm.", emoji: "🌹", guide: "Âm h và th: hoa hồng / hương thơm", theme: "from-pink-200 via-rose-100 to-purple-200", textColor: "text-pink-900" },
    { id: 260, text: "Bé quét dọn góc học tập.", emoji: "🧹", guide: "Vần et và âm gi: quét dọn", theme: "from-teal-200 via-cyan-100 to-emerald-200", textColor: "text-teal-900" },
    { id: 261, text: "Mặt trời chiếu nắng ấm.", emoji: "☀️", guide: "Âm tr và ch: mặt trời chiếu", theme: "from-yellow-200 via-orange-100 to-rose-200", textColor: "text-amber-900" },
    { id: 262, text: "Bé đi ngủ sớm mỗi tối.", emoji: "🌙", guide: "Âm s và vần ơi: sớm / tối", theme: "from-purple-200 via-violet-100 to-sky-200", textColor: "text-purple-900" },
    { id: 263, text: "Gà trống gáy vang buổi sớm.", emoji: "🐓", guide: "Âm tr và s: trống / buổi sớm", theme: "from-orange-200 via-amber-100 to-rose-200", textColor: "text-orange-900" },
    { id: 264, text: "Vườn rau xanh mơn mởn.", emoji: "🥬", guide: "Vần ơn: mơn mởn", theme: "from-emerald-200 via-green-100 to-teal-200", textColor: "text-emerald-900" },
    { id: 265, text: "Bé lau khô đôi tay.", emoji: "🙌", guide: "Vần au và ay: lau khô đôi tay", theme: "from-sky-200 via-blue-100 to-indigo-200", textColor: "text-sky-900" },
    { id: 266, text: "Bố đọc báo buổi sớm.", emoji: "📰", guide: "Vần ao và uôi: báo buổi sớm", theme: "from-amber-200 via-yellow-100 to-orange-200", textColor: "text-amber-900" },
    { id: 267, text: "Bà nhai trầu đỏ tươi.", emoji: "👵", guide: "Âm tr và vần au: trầu đỏ tươi", theme: "from-rose-200 via-pink-100 to-red-200", textColor: "text-rose-900" },
    { id: 268, text: "Bé uống hết ly sữa.", emoji: "🥛", guide: "Dấu ngã: ly sữa", theme: "from-teal-200 via-cyan-100 to-blue-200", textColor: "text-teal-900" },
    { id: 269, text: "Tiếng ve kêu rộn rã.", emoji: "🦗", guide: "Dấu ngã: rộn rã", theme: "from-orange-200 via-red-100 to-amber-200", textColor: "text-orange-900" },
    { id: 270, text: "Bé tô màu bức tranh.", emoji: "🖍️", guide: "Âm tr: bức tranh", theme: "from-indigo-200 via-purple-100 to-teal-200", textColor: "text-indigo-900" },
    { id: 271, text: "Con suối reo trong vắt.", emoji: "💧", guide: "Âm s: con suối trong vắt", theme: "from-sky-200 via-cyan-100 to-teal-200", textColor: "text-sky-900" },
    { id: 272, text: "Bé nhổ cỏ quanh gốc hoa.", emoji: "🌱", guide: "Dấu hỏi: nhổ cỏ", theme: "from-green-200 via-lime-100 to-emerald-200", textColor: "text-green-900" },
    { id: 273, text: "Mẹ cắt móng tay cho bé.", emoji: "✂️", guide: "Vần ong và ay: móng tay", theme: "from-pink-200 via-rose-100 to-amber-200", textColor: "text-pink-900" },
    { id: 274, text: "Bé chải tóc thật mượt.", emoji: "💇", guide: "Vần ươt: thật mượt", theme: "from-teal-200 via-emerald-100 to-green-200", textColor: "text-teal-900" },
    { id: 275, text: "Đàn cá bơi lội dưới ao.", emoji: "🐟", guide: "Vần ơi và ôi: bơi lội", theme: "from-sky-200 via-blue-100 to-cyan-200", textColor: "text-sky-900" },
    { id: 276, text: "Bé xếp gọn giá giày dép.", emoji: "👞", guide: "Âm gi và d: giá giày dép", theme: "from-amber-200 via-yellow-100 to-lime-200", textColor: "text-amber-900" },
    { id: 277, text: "Bé không nói chuyện riêng.", emoji: "🤫", guide: "Vần uyên và iêng: chuyện riêng", theme: "from-purple-200 via-violet-100 to-pink-200", textColor: "text-purple-900" },
    { id: 278, text: "Hoa cúc khoe sắc vàng.", emoji: "🌼", guide: "Vần oe: khoe sắc vàng", theme: "from-yellow-200 via-amber-100 to-orange-200", textColor: "text-amber-800" },
    { id: 279, text: "Bé tự xúc cơm ăn.", emoji: "🍚", guide: "Âm x: xúc cơm ăn", theme: "from-rose-200 via-pink-100 to-amber-200", textColor: "text-rose-900" },
    { id: 280, text: "Gió lay nhẹ cành đào.", emoji: "🌸", guide: "Vần ay: lay nhẹ cành", theme: "from-pink-200 via-purple-100 to-rose-200", textColor: "text-pink-900" },
    { id: 281, text: "Bé tập nhảy dây vui vẻ.", emoji: "🪢", guide: "Dấu hỏi: nhảy dây vui vẻ", theme: "from-emerald-200 via-teal-100 to-green-200", textColor: "text-emerald-900" },
    { id: 282, text: "Bố đóng kệ sách mới cho bé.", emoji: "🪵", guide: "Âm đ và s: đóng kệ sách", theme: "from-amber-200 via-orange-100 to-yellow-200", textColor: "text-amber-900" },
    { id: 283, text: "Bé vâng lời bố mẹ dặn.", emoji: "🙏", guide: "Âm v: vâng lời", theme: "from-indigo-200 via-sky-100 to-blue-200", textColor: "text-indigo-900" },
    { id: 284, text: "Chim sáo hót líu lo.", emoji: "🐦", guide: "Âm s và l: sáo / líu lo", theme: "from-sky-200 via-blue-100 to-cyan-200", textColor: "text-sky-900" },
    { id: 285, text: "Bé yêu thương ông bà.", emoji: "🧓", guide: "Vần ương: yêu thương", theme: "from-rose-200 via-amber-100 to-pink-200", textColor: "text-rose-900" },
    { id: 286, text: "Đèn đỏ bé dừng lại bên đường.", emoji: "🚦", guide: "Ngắt: Đèn đỏ / bé dừng lại", theme: "from-orange-200 via-rose-100 to-amber-200", textColor: "text-orange-900" },
    { id: 287, text: "Trái bưởi chín vàng ươm.", emoji: "🍐", guide: "Vần ươi và ươm: bưởi chín", theme: "from-yellow-200 via-lime-100 to-emerald-200", textColor: "text-amber-900" },
    { id: 288, text: "Bé lau bảng giúp cô.", emoji: "🧽", guide: "Vần au và ang: lau bảng", theme: "from-teal-200 via-cyan-100 to-emerald-200", textColor: "text-teal-900" },
    { id: 289, text: "Chiếc cặp sách màu xanh.", emoji: "🎒", guide: "Âm s và x: sách màu xanh", theme: "from-sky-200 via-indigo-100 to-blue-200", textColor: "text-sky-900" },
    { id: 290, text: "Mẹ may cho bé chiếc váy đẹp.", emoji: "👗", guide: "Vần ay: may cho bé", theme: "from-purple-200 via-pink-100 to-rose-200", textColor: "text-purple-900" },
    { id: 291, text: "Bé giữ trật tự trong lớp.", emoji: "🤫", guide: "Âm tr: trật tự", theme: "from-emerald-200 via-teal-100 to-green-200", textColor: "text-emerald-900" },
    { id: 292, text: "Cơn gió mùa thu mát dịu.", emoji: "🍃", guide: "Vần iu: mát dịu", theme: "from-amber-200 via-yellow-100 to-orange-200", textColor: "text-amber-900" },
    { id: 293, text: "Bé ăn nhiều rau xanh.", emoji: "🥦", guide: "Vần au và anh: rau xanh", theme: "from-green-200 via-emerald-100 to-teal-200", textColor: "text-green-900" },
    { id: 294, text: "Đàn bướm bay lượn quanh.", emoji: "🦋", guide: "Vần ươm và uơn: bướm bay lượn", theme: "from-pink-200 via-rose-100 to-purple-200", textColor: "text-pink-900" },
    { id: 295, text: "Bé chào tạm biệt cô.", emoji: "👋", guide: "Vần iêt: tạm biệt", theme: "from-sky-200 via-blue-100 to-cyan-200", textColor: "text-sky-900" },
    { id: 296, text: "Đồng hồ reo reng reng.", emoji: "⏰", guide: "Vần eng: reo reng reng", theme: "from-orange-200 via-amber-100 to-yellow-200", textColor: "text-orange-900" },
    { id: 297, text: "Bé mỉm cười chào khách.", emoji: "😊", guide: "Vần im và ach: mỉm cười / khách", theme: "from-rose-200 via-pink-100 to-red-200", textColor: "text-rose-900" },
    { id: 298, text: "Bàn tay bé nhỏ xinh xắn.", emoji: "🖐️", guide: "Âm x: nhỏ xinh xắn", theme: "from-amber-200 via-orange-100 to-yellow-200", textColor: "text-amber-900" },
    { id: 299, text: "Bé viết bài nhanh và đúng.", emoji: "✍️", guide: "Vần anh và ung: nhanh và đúng", theme: "from-teal-200 via-emerald-100 to-cyan-200", textColor: "text-teal-900" },
    { id: 300, text: "Bé là bông hoa điểm mười.", emoji: "💯", guide: "Vần oa và ươi: hoa điểm mười", theme: "from-rose-300 via-amber-200 to-pink-200", textColor: "text-rose-900" }
  ],
  level3: [
    { id: 301, text: "Bé khoanh tay lễ phép.", emoji: "🙇‍♂️", guide: "Vần oanh tròn môi: khoanh tay", theme: "from-sky-200 via-cyan-100 to-teal-200", textColor: "text-sky-900" },
    { id: 302, text: "Vườn xoài chín thơm lừng.", emoji: "🥭", guide: "Tròn môi ở vần oai: vườn xoài", theme: "from-amber-200 via-yellow-100 to-orange-200", textColor: "text-amber-900" },
    { id: 303, text: "Bé xòe bàn tay nhỏ.", emoji: "🖐️", guide: "Vần oe mở rộng: bé xòe", theme: "from-rose-200 via-pink-100 to-purple-200", textColor: "text-rose-900" },
    { id: 304, text: "Chiếc thuyền lướt trên sóng.", emoji: "⛵", guide: "Vần uyên: chiếc thuyền", theme: "from-teal-200 via-sky-100 to-indigo-200", textColor: "text-teal-900" },
    { id: 305, text: "Cánh diều bay lượn trên cao.", emoji: "🪁", guide: "Vần iêu và ươn: bay lượn", theme: "from-purple-200 via-indigo-100 to-pink-200", textColor: "text-purple-900" },
    { id: 306, text: "Đoàn tàu bấm còi tu tu.", emoji: "🚂", guide: "Vần oan tròn môi: đoàn tàu", theme: "from-orange-200 via-amber-100 to-red-200", textColor: "text-orange-900" },
    { id: 307, text: "Bé mặc áo len ấm áp.", emoji: "🧥", guide: "Vần ăc và vần ap rõ ràng", theme: "from-green-200 via-emerald-100 to-teal-200", textColor: "text-green-900" },
    { id: 308, text: "Khuyên tai mẹ lấp lánh.", emoji: "✨", guide: "Vần uyên trong tiếng: khuyên", theme: "from-indigo-200 via-purple-100 to-sky-200", textColor: "text-indigo-900" },
    { id: 309, text: "Bé ngoan ngoãn vâng lời.", emoji: "😇", guide: "Phân biệt: ngoan - ngoãn", theme: "from-amber-200 via-orange-100 to-yellow-200", textColor: "text-amber-900" },
    { id: 310, text: "Con suối lượn quanh co.", emoji: "🏞️", guide: "Âm s uốn lưỡi: suối lượn", theme: "from-sky-200 via-teal-100 to-cyan-200", textColor: "text-sky-900" },
    { id: 311, text: "Đường lên dốc khúc khuỷu.", emoji: "🛤️", guide: "Vần uyu khó: khúc khuỷu", theme: "from-teal-200 via-green-100 to-emerald-200", textColor: "text-teal-900" },
    { id: 312, text: "Bé giữ gìn sách cẩn thận.", emoji: "📚", guide: "Âm gi đọc nhẹ: giữ gìn", theme: "from-rose-200 via-pink-100 to-amber-200", textColor: "text-rose-900" },
    { id: 313, text: "Chim khuyên hót líu lo.", emoji: "🐦", guide: "Vần uyên và iu: chim khuyên", theme: "from-amber-200 via-yellow-100 to-lime-200", textColor: "text-amber-900" },
    { id: 314, text: "Búp bê mặc váy hoa xoan.", emoji: "👗", guide: "Tròn môi: hoa xoan", theme: "from-purple-200 via-pink-100 to-indigo-200", textColor: "text-purple-900" },
    { id: 315, text: "Bé uống nước quả ngọt mát.", emoji: "🍹", guide: "Vần uông và at: ngọt mát", theme: "from-green-200 via-teal-100 to-emerald-200", textColor: "text-green-900" },
    { id: 316, text: "Chú bộ đội duyệt binh.", emoji: "🎖️", guide: "Vần uyêt: duyệt binh", theme: "from-orange-200 via-red-100 to-yellow-200", textColor: "text-orange-900" },
    { id: 317, text: "Bàn tay bé thoăn thoắt.", emoji: "👐", guide: "Vần oăn - oăt: thoăn thoắt", theme: "from-sky-200 via-cyan-100 to-blue-200", textColor: "text-sky-900" },
    { id: 318, text: "Cây chuối trổ buồng xanh.", emoji: "🍌", guide: "Âm tr và vần uông: trổ buồng", theme: "from-indigo-200 via-teal-100 to-sky-200", textColor: "text-indigo-900" },
    { id: 319, text: "Gió heo may se se lạnh.", emoji: "🌾", guide: "Từ láy dịu nhẹ: se se lạnh", theme: "from-amber-200 via-orange-100 to-rose-200", textColor: "text-amber-900" },
    { id: 320, text: "Bé chăm chỉ luyện chữ.", emoji: "📝", guide: "Vần uyên: luyện chữ", theme: "from-green-200 via-emerald-100 to-lime-200", textColor: "text-green-900" },
    { id: 321, text: "Bé huơ tay đón bố về.", emoji: "👋", guide: "Vần uơ: huơ tay", theme: "from-rose-200 via-pink-100 to-amber-200", textColor: "text-rose-800" },
    { id: 322, text: "Cây hoa giấy nở xum xuê.", emoji: "🌼", guide: "Vần uê: nở xum xuê", theme: "from-amber-200 via-orange-100 to-yellow-200", textColor: "text-amber-900" },
    { id: 323, text: "Chú cún chạy quýnh quáng.", emoji: "🐕", guide: "Vần uynh - uang: quýnh quáng", theme: "from-emerald-200 via-teal-100 to-green-200", textColor: "text-emerald-900" },
    { id: 324, text: "Chú cảnh sát tuýt còi xin đường.", emoji: "📢", guide: "Vần uyt: tuýt còi", theme: "from-sky-200 via-blue-100 to-cyan-200", textColor: "text-sky-900" },
    { id: 325, text: "Vườn hoa huệ trắng ngần.", emoji: "🪻", guide: "Vần uê: hoa huệ", theme: "from-purple-200 via-violet-100 to-pink-200", textColor: "text-purple-900" },
    { id: 326, text: "Bé mở toang cánh cửa sổ.", emoji: "🪟", guide: "Vần oang: mở toang", theme: "from-orange-200 via-amber-100 to-rose-200", textColor: "text-orange-900" },
    { id: 327, text: "Bạn Nga mặc áo khoác đỏ.", emoji: "🧥", guide: "Vần oac: áo khoác", theme: "from-teal-200 via-cyan-100 to-emerald-200", textColor: "text-teal-900" },
    { id: 328, text: "Cây xoan đung đưa cành.", emoji: "🌳", guide: "Vần oan: cây xoan", theme: "from-indigo-200 via-sky-100 to-blue-200", textColor: "text-indigo-900" },
    { id: 329, text: "Bé khoe chiếc huy hiệu.", emoji: "🏅", guide: "Vần uy: huy hiệu", theme: "from-rose-200 via-pink-100 to-red-200", textColor: "text-rose-900" },
    { id: 330, text: "Bầu trời đêm đầy sao khuya.", emoji: "🌌", guide: "Vần uya: sao khuya", theme: "from-amber-200 via-yellow-100 to-lime-200", textColor: "text-amber-900" },
    { id: 331, text: "Bé nhảy lò cò thoăn thoắt.", emoji: "🤸", guide: "Vần oăt: thoăn thoắt", theme: "from-sky-200 via-indigo-100 to-blue-200", textColor: "text-sky-900" },
    { id: 332, text: "Suối nước chảy róc rách.", emoji: "🏞️", guide: "Âm s và ch: róc rách", theme: "from-amber-200 via-orange-100 to-yellow-200", textColor: "text-amber-900" },
    { id: 333, text: "Bé giải bài toán rất nhanh.", emoji: "🧮", guide: "Vần oan: bài toán", theme: "from-yellow-200 via-amber-100 to-orange-200", textColor: "text-amber-800" },
    { id: 334, text: "Khóm tre nghiêng bóng mát.", emoji: "🎋", guide: "Vần iêng: nghiêng bóng mát", theme: "from-teal-200 via-cyan-100 to-emerald-200", textColor: "text-teal-900" },
    { id: 335, text: "Tiếng ve kêu râm ran.", emoji: "🦗", guide: "Từ láy: râm ran", theme: "from-cyan-200 via-teal-100 to-emerald-200", textColor: "text-teal-900" },
    { id: 336, text: "Bé ngoan được tặng phiếu khen.", emoji: "🎫", guide: "Vần iêu: phiếu khen", theme: "from-orange-200 via-rose-100 to-amber-200", textColor: "text-orange-900" },
    { id: 337, text: "Chim chuyền cành thoăn thoắt.", emoji: "🐦", guide: "Vần uyên và oăt", theme: "from-emerald-200 via-green-100 to-lime-200", textColor: "text-emerald-900" },
    { id: 338, text: "Bố khuấy đều ly sữa nóng.", emoji: "☕", guide: "Vần uây: khuấy đều", theme: "from-rose-200 via-amber-100 to-pink-200", textColor: "text-rose-900" },
    { id: 339, text: "Bé chạy huỳnh huỵch ngoài sân.", emoji: "🏃", guide: "Vần uynh - uych khó", theme: "from-pink-200 via-purple-100 to-rose-200", textColor: "text-pink-900" },
    { id: 340, text: "Vườn đào hé nở hoa tươi.", emoji: "🌺", guide: "Vần oa và ươi: hoa tươi", theme: "from-green-200 via-emerald-100 to-teal-200", textColor: "text-green-900" },
    { id: 341, text: "Bé khoác vai bạn thân.", emoji: "🫂", guide: "Vần oac: khoác vai", theme: "from-rose-200 via-pink-100 to-amber-200", textColor: "text-rose-800" },
    { id: 342, text: "Ngọn đuốc sáng rực rỡ.", emoji: "🔥", guide: "Vần uôc: ngọn đuốc", theme: "from-amber-200 via-orange-100 to-yellow-200", textColor: "text-amber-900" },
    { id: 343, text: "Đoàn kết là sức mạnh.", emoji: "🤝", guide: "Vần oan: đoàn kết", theme: "from-emerald-200 via-teal-100 to-green-200", textColor: "text-emerald-900" },
    { id: 344, text: "Bé huýt sáo vang rộn ràng.", emoji: "😙", guide: "Vần uyt và r: huýt sáo rộn ràng", theme: "from-sky-200 via-blue-100 to-cyan-200", textColor: "text-sky-900" },
    { id: 345, text: "Lá vàng bay xoay tít trong gió.", emoji: "🍂", guide: "Vần oay: xoay tít", theme: "from-purple-200 via-violet-100 to-pink-200", textColor: "text-purple-900" },
    { id: 346, text: "Bé múa dẻo như tiên.", emoji: "🧚", guide: "Vần ua và iên: múa dẻo", theme: "from-orange-200 via-amber-100 to-rose-200", textColor: "text-orange-900" },
    { id: 347, text: "Con đường làng quanh co.", emoji: "🛤️", guide: "Vần oanh: quanh co", theme: "from-teal-200 via-cyan-100 to-emerald-200", textColor: "text-teal-900" },
    { id: 348, text: "Vườn cam sai trĩu cành.", emoji: "🍊", guide: "Âm s và tr: sai trĩu", theme: "from-indigo-200 via-sky-100 to-blue-200", textColor: "text-indigo-900" },
    { id: 349, text: "Bé đọc thơ lưu loát.", emoji: "📖", guide: "Vần oat: lưu loát", theme: "from-rose-200 via-pink-100 to-red-200", textColor: "text-rose-900" },
    { id: 350, text: "Mẹ mỉm cười xoa đầu bé.", emoji: "🤱", guide: "Vần oa tròn môi: xoa đầu", theme: "from-amber-200 via-yellow-100 to-lime-200", textColor: "text-amber-900" },
    { id: 351, text: "Bé huơ tay vẫy chào chú hải quân.", emoji: "⚓", guide: "Vần uơ: huơ tay vẫy chào", theme: "from-sky-200 via-blue-100 to-cyan-200", textColor: "text-sky-900" },
    { id: 352, text: "Hoa vạn thọ xum xuê trước ngõ.", emoji: "🌼", guide: "Vần uê: xum xuê trước ngõ", theme: "from-amber-200 via-yellow-100 to-orange-200", textColor: "text-amber-900" },
    { id: 353, text: "Bé xem biểu diễn xiếc khỉ vui nhộn.", emoji: "🐵", guide: "Vần iêu và iêc: biểu diễn xiếc", theme: "from-purple-200 via-pink-100 to-rose-200", textColor: "text-purple-900" },
    { id: 354, text: "Chiếc xích đu đung đưa dưới bóng mát.", emoji: "🎪", guide: "Vần ich và uô: xích đu / bóng mát", theme: "from-teal-200 via-sky-100 to-indigo-200", textColor: "text-teal-900" },
    { id: 355, text: "Bé cùng mẹ khuấy nồi chè đậu xanh.", emoji: "🍲", guide: "Vần uây: khuấy nồi chè", theme: "from-orange-200 via-amber-100 to-yellow-200", textColor: "text-orange-900" },
    { id: 356, text: "Tiếng chim hót ríu rít trên ngọn cây.", emoji: "🐦", guide: "Âm r: ríu rít trên ngọn cây", theme: "from-emerald-200 via-green-100 to-teal-200", textColor: "text-emerald-900" },
    { id: 357, text: "Bé lau sạch chiếc gương tròn xoe.", emoji: "🪞", guide: "Tròn môi vần oe: tròn xoe", theme: "from-sky-200 via-cyan-100 to-blue-200", textColor: "text-sky-900" },
    { id: 358, text: "Đoàn xe lửa chạy xình xịch qua đèo.", emoji: "🚂", guide: "Vần oan và ich: đoàn xe lửa", theme: "from-indigo-200 via-purple-100 to-sky-200", textColor: "text-indigo-900" },
    { id: 359, text: "Bé mặc áo len cổ lọ màu tuyết trắng.", emoji: "❄️", guide: "Vần uyêt: màu tuyết trắng", theme: "from-rose-200 via-pink-100 to-amber-200", textColor: "text-rose-900" },
    { id: 360, text: "Bé chạy lon ton theo mẹ ra chợ hoa.", emoji: "💐", guide: "Vần on và oa: lon ton / chợ hoa", theme: "from-pink-200 via-rose-100 to-purple-200", textColor: "text-pink-900" },
    { id: 361, text: "Chú cún mừng quýnh vẫy đuôi đón bé.", emoji: "🐶", guide: "Vần uynh: mừng quýnh", theme: "from-amber-200 via-orange-100 to-yellow-200", textColor: "text-amber-900" },
    { id: 362, text: "Bé xòe ngón tay đếm từ một đến mười.", emoji: "🔢", guide: "Vần oe: xòe ngón tay", theme: "from-teal-200 via-emerald-100 to-green-200", textColor: "text-teal-900" },
    { id: 363, text: "Dòng suối trong veo lượn quanh xóm nhỏ.", emoji: "🏞️", guide: "Vần eo và uơn: trong veo / lượn", theme: "from-cyan-200 via-teal-100 to-emerald-200", textColor: "text-teal-900" },
    { id: 364, text: "Bé đọc to bài văn trước cả lớp.", emoji: "📖", guide: "Âm đ và tr: đọc to / trước lớp", theme: "from-rose-200 via-pink-100 to-red-200", textColor: "text-rose-900" },
    { id: 365, text: "Vườn hoa ngát hương thơm trong nắng sớm.", emoji: "🌺", guide: "Vần ươn và ang: ngát hương thơm", theme: "from-green-200 via-emerald-100 to-lime-200", textColor: "text-green-900" },
    { id: 366, text: "Bé xếp hình tòa lâu đài thật lộng lẫy.", emoji: "🏰", guide: "Dấu ngã: lộng lẫy", theme: "from-purple-200 via-violet-100 to-pink-200", textColor: "text-purple-900" },
    { id: 367, text: "Mẹ gọt đĩa hoa quả ngọt ngào cho bé.", emoji: "🍎", guide: "Vần oa và ao: hoa quả ngọt ngào", theme: "from-orange-200 via-amber-100 to-rose-200", textColor: "text-orange-900" },
    { id: 368, text: "Bé thổi kèn vang lên từng khúc nhạc.", emoji: "🎺", guide: "Vần oi và en: thổi kèn", theme: "from-yellow-200 via-amber-100 to-orange-200", textColor: "text-amber-800" },
    { id: 369, text: "Bố dạy bé cách buộc dây giày thật chặt.", emoji: "👟", guide: "Vần uôc và ay: buộc dây giày", theme: "from-sky-200 via-blue-100 to-indigo-200", textColor: "text-sky-900" },
    { id: 370, text: "Chim sáo nâu nhảy nhót trên cành bàng.", emoji: "🐦", guide: "Âm s và n: sáo nâu nhảy nhót", theme: "from-emerald-200 via-teal-100 to-green-200", textColor: "text-emerald-900" },
    { id: 371, text: "Bé ngắm bông hoa hồng nhung thơm ngát.", emoji: "🌹", guide: "Vần ơi và ung: hoa hồng nhung", theme: "from-rose-200 via-pink-100 to-purple-200", textColor: "text-rose-900" },
    { id: 372, text: "Bầu trời mùa đông nhiều mây xám xịt.", emoji: "☁️", guide: "Âm x: xám xịt", theme: "from-teal-200 via-cyan-100 to-emerald-200", textColor: "text-teal-900" },
    { id: 373, text: "Bé cùng bạn dạo chơi quanh hồ sen.", emoji: "🪷", guide: "Vần ao và en: dạo chơi / hồ sen", theme: "from-pink-200 via-rose-100 to-amber-200", textColor: "text-pink-900" },
    { id: 374, text: "Bà vuốt tóc khen bé rất ngoan ngoãn.", emoji: "👵", guide: "Tròn môi: ngoan ngoãn", theme: "from-amber-200 via-yellow-100 to-lime-200", textColor: "text-amber-900" },
    { id: 375, text: "Chiếc thuyền buồm đỏ thắm lướt ra khơi.", emoji: "⛵", guide: "Vần uyên và uôm: thuyền buồm", theme: "from-sky-200 via-cyan-100 to-blue-200", textColor: "text-sky-900" },
    { id: 376, text: "Bé vẽ quả dưa hấu đỏ ngọt lịm.", emoji: "🍉", guide: "Vần ưa và âu: dưa hấu đỏ", theme: "from-rose-200 via-pink-100 to-amber-200", textColor: "text-rose-900" },
    { id: 377, text: "Bé rửa sạch cốc nước sau khi uống.", emoji: "🥛", guide: "Vần ôc và uông: cốc nước", theme: "from-teal-200 via-emerald-100 to-cyan-200", textColor: "text-teal-900" },
    { id: 378, text: "Tiếng cười giòn giã vang khắp góc sân.", emoji: "😆", guide: "Âm gi và dấu ngã: giòn giã", theme: "from-orange-200 via-amber-100 to-yellow-200", textColor: "text-orange-900" },
    { id: 379, text: "Đàn kiến cần cù tha mồi về tổ.", emoji: "🐜", guide: "Vần iên và ân: kiến cần cù", theme: "from-amber-200 via-orange-100 to-yellow-200", textColor: "text-amber-900" },
    { id: 380, text: "Bé không đùa nghịch trong lớp học.", emoji: "🏫", guide: "Vần ua và ich: đùa nghịch", theme: "from-indigo-200 via-sky-100 to-blue-200", textColor: "text-indigo-900" },
    { id: 381, text: "Cánh hoa đào bay lả tả trong làn gió xuân.", emoji: "🌸", guide: "Dấu hỏi: bay lả tả trong gió", theme: "from-pink-200 via-purple-100 to-rose-200", textColor: "text-pink-900" },
    { id: 382, text: "Bé gấp chiếc thuyền giấy màu vàng tươi.", emoji: "🚢", guide: "Vần uyên và ươi: thuyền giấy / tươi", theme: "from-yellow-200 via-amber-100 to-orange-200", textColor: "text-amber-800" },
    { id: 383, text: "Bé lau sạch bảng đen giúp cô giáo.", emoji: "🧽", guide: "Vần ang và en: bảng đen", theme: "from-teal-200 via-cyan-100 to-emerald-200", textColor: "text-teal-900" },
    { id: 384, text: "Con đường làng uốn lượn bên bờ kênh.", emoji: "🏞️", guide: "Vần uơn và ênh: uốn lượn / kênh", theme: "from-green-200 via-emerald-100 to-teal-200", textColor: "text-green-900" },
    { id: 385, text: "Bé cẩn thận gọt từng chiếc bút chì.", emoji: "✏️", guide: "Âm c và ch: cẩn thận / bút chì", theme: "from-orange-200 via-rose-100 to-amber-200", textColor: "text-orange-900" },
    { id: 386, text: "Bác bảo vệ đánh trống báo giờ tan học.", emoji: "🥁", guide: "Âm tr và an: trống / tan học", theme: "from-sky-200 via-blue-100 to-cyan-200", textColor: "text-sky-900" },
    { id: 387, text: "Bé giữ gìn sách vở luôn sạch sẽ.", emoji: "📚", guide: "Âm gi và s: giữ gìn / sạch sẽ", theme: "from-emerald-200 via-teal-100 to-green-200", textColor: "text-emerald-900" },
    { id: 388, text: "Bé nắm tay em nhỏ dắt qua đường.", emoji: "🤝", guide: "Âm d và tr: dắt qua đường", theme: "from-rose-200 via-amber-100 to-pink-200", textColor: "text-rose-900" },
    { id: 389, text: "Những tia nắng ấm rọi sáng gian phòng.", emoji: "☀️", guide: "Vần ia và ang: tia nắng / sáng", theme: "from-amber-200 via-yellow-100 to-orange-200", textColor: "text-amber-900" },
    { id: 390, text: "Bé tưới khóm hoa mười giờ rực rỡ.", emoji: "🌺", guide: "Âm r: rực rỡ", theme: "from-purple-200 via-pink-100 to-rose-200", textColor: "text-purple-900" },
    { id: 391, text: "Bé làm xong bài tập cô giao về nhà.", emoji: "📝", guide: "Âm b và g: bài tập / giao", theme: "from-teal-200 via-cyan-100 to-emerald-200", textColor: "text-teal-900" },
    { id: 392, text: "Cơn mưa rào tạnh hẳn trời lại sáng trong.", emoji: "🌈", guide: "Âm r và tr: mưa rào / sáng trong", theme: "from-sky-200 via-indigo-100 to-blue-200", textColor: "text-sky-900" },
    { id: 393, text: "Bé lễ phép thưa gửi với người lớn.", emoji: "🙇", guide: "Vần ưa và ửi: thưa gửi", theme: "from-rose-200 via-pink-100 to-amber-200", textColor: "text-rose-900" },
    { id: 394, text: "Mẹ may cho bé chiếc khẩu trang xinh.", emoji: "😷", guide: "Vần âu và ang: khẩu trang xinh", theme: "from-pink-200 via-purple-100 to-rose-200", textColor: "text-pink-900" },
    { id: 395, text: "Bé biết nói lời cảm ơn chân thành.", emoji: "💐", guide: "Vần ơn và ân: cảm ơn / chân thành", theme: "from-emerald-200 via-green-100 to-teal-200", textColor: "text-emerald-900" },
    { id: 396, text: "Đàn vịt con bơi lội dưới bóng tre.", emoji: "🦆", guide: "Vần ơi và ôi: bơi lội", theme: "from-yellow-200 via-amber-100 to-lime-200", textColor: "text-amber-900" },
    { id: 397, text: "Bé giúp mẹ quét sân sạch bóng.", emoji: "🧹", guide: "Vần et và âm s: quét sân sạch", theme: "from-teal-200 via-cyan-100 to-emerald-200", textColor: "text-teal-900" },
    { id: 398, text: "Bé chăm ngoan được cô tặng hoa điểm mười.", emoji: "💮", guide: "Tròn môi: chăm ngoan / hoa điểm mười", theme: "from-rose-200 via-pink-100 to-red-200", textColor: "text-rose-900" },
    { id: 399, text: "Mỗi ngày bé học thêm nhiều điều mới lạ.", emoji: "💡", guide: "Vần iêu và ơi: nhiều điều mới lạ", theme: "from-amber-200 via-orange-100 to-yellow-200", textColor: "text-amber-900" },
    { id: 400, text: "Bé đọc sách chăm chỉ để mở mang kiến thức.", emoji: "📚", guide: "Âm ch và k: chăm chỉ / kiến thức", theme: "from-sky-300 via-teal-200 to-indigo-200", textColor: "text-indigo-950" }
  ]
};
